name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=cov.out ./...

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: cov.out

  sonarcloud:
    name: SonarCloud analysis
    needs:
      build
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}

    permissions:
      pull-requests: read # allows SonarCloud to decorate PRs with analysis results
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
