name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build
      run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go build -v ./...

    - name: Test
      run: GOOS=${{matrix.os}} GOARCH=${{matrix.arch}} go test -v ./...
