name: SonarCloud

on:
  workflow_run:
    workflows: ["Build"]
    types: 
      - completed

jobs:
  sonarcloud:
    name: SonarCloud analysis
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read # allows SonarCloud to decorate PRs with analysis results
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download code coverage results
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
